### ISSUE TITLE
(WotLK) Filter by a different Character's Completion

### ISSUE THREAD

**Issue by itBagel** [DFortun81/ATT-WRATH-Classic#12]
Due to achievements being character specific instead of account wide in wrath, I (and I assume others) selected a main to work on as my character to shoot for as close to 100% as I can get. It would be helpful to be able to sort by that character's completion when I'm on other characters - specifically bank alts. 

Account Mode is similar to this request and maybe I could tweak the character exclusion settings to trigger this? However, the ability to select which character to track would be helpful. i.e. Bank alt tracking main's completion for the purposes of AH scanning. Another character tracking their own completion as they level, without having to tweak settings each time.

**Comment by DFortun81** [comment]
Unfortunately this isn't something we can support. A lot of the validation for items on your current character depend on that character's active inventory and skills and so even if I did find a way to tweak the display to use your main's data, it would overwrite it when it determines the items/skills are no longer found on that character.
