### ISSUE TITLE
Glyphs Missing from version 1.1.0

### ISSUE THREAD

**Issue by Forthehorde2022** [DFortun81/ATT-WRATH-Classic#13]
The following are missing from ATT database version 1.1.0

Glyph of the ghoul
Glyph of vampiric blood
Glyph of death strike
Glyph of blood strike
Glyph of rune tap
Glyph of unbreakable armor
Glyph of plague strike
Glyph of frenzied regeneration
Glyph of rake
Glyph of shred
Glyph of starfire
Glyph of frost trap
Glyph of rapid fire
Glyph of arcane power
Glyph of mage armor
Glyph of arcane blast
Glyph of ice block
Glyph of seal of command
Glyph of flash of light
Glyph of shadow word: Pain
Glyph of holy nova
Glyph of ambush
Glyph of feint
Glyph of garrotte
Glyph of thunderstorm
Glyph of windfury weapon
Glyph of earthliving weapon
Glyph of lava lash
Glyph of incinerate
Glyph of succubus
Glyph of whirlwind
Glyph of sweeping strikes

**Comment by DFortun81** [comment]
This has been fixed in 1.4.6. Please let me know with a new ticket otherwise!
