### ISSUE TITLE
When opening Profession (Enchanting) it say no Profession Opened.

### ISSUE THREAD

**Issue by Taiyuki** [DFortun81/ATT-WRATH-Classic#14]
After Wotlk came out, I cannot open my enchanting window by clicking the button on my bar. It opens TSM but it just says Loading... and that there is no Profession opened.

**Comment by DFortun81** [comment]
Try again in 1.1.8 and make sure Recipes are turned on. Please reopen and supply a screenshot if it's still happening to you.
