### ISSUE TITLE
Incorrect Coordinates for vendors in Wrath Classic

### ISSUE THREAD

**Issue by DTM96** [DFortun81/ATT-WRATH-Classic#16]
Don't know if this is a known issue or not. 

When using this mod to look for recipe vendors in Stormwind I noticed that the coordinates for all the ones I looked at are wrong in the list (Kendor Kabonka for instance is said to be at 74.6, 36.8 according to the mod, putting him in the keep, but he is actually in an inn in old town at 77.46, 52.68). I thought the mod might be showing Cata cords, but that does not appear to be the case.

I don't know if this a more far reaching issue that affects other 'things' in the collection as I haven't checked anything but these vendors.

**Comment by DFortun81** [comment]
This appears to have been corrected when the Stormwind City file was updated.
