### ISSUE TITLE
Getting Lua Error on Sign In and Loot

### ISSUE THREAD

**Issue by Gogo1951** [DFortun81/ATT-WRATH-Classic#19]
5x ATT-Classic\ATT-Classic-1.1.6.lua:69: ATT-Classic\ATT-Classic.lua:3802: attempt to compare nil with number
[string "=[C]"]: in function `error'
[string "@ATT-Classic\ATT-Classic-1.1.6.lua"]:98: in function `?'
[string "@ATT-Classic\ATT-Classic-1.1.6.lua"]:69: in function <ATT-Classic\ATT-Classic.lua:67>
[string "@ATT-Classic\src\base.lua"]:33: in function <ATT-Classic\src\base.lua:32>

Locals:
(*temporary) = "ATT-Classic\ATT-Classic.lua:3802: attempt to compare nil with number"

**Comment by DFortun81** [comment]
This has been fixed as of 1.1.8
