### ISSUE TITLE
[Wrath Classic] Addon doesn't register Minipets/Battle Pets once learned

### ISSUE THREAD

**Issue by aSnejbjerg** [DFortun81/ATT-WRATH-Classic#2]
It seems whenever you learn a Minipet it forgets that you have that pet. For example with the Rabbit Snowshoe from Dun Morogh:
![image](https://user-images.githubusercontent.com/42168095/187764941-51823343-74d2-41df-ae6e-7a28c2a80d27.png)

**Comment by DFortun81** [comment]
This has been fixed on Git!
