### ISSUE TITLE
JC Recipes Missing from Northrend

### ISSUE THREAD

**Issue by GaryOakRobotron** [DFortun81/ATT-WRATH-Classic#22]
https://i.imgur.com/1tAVl93.png

There are many JC recipes that I don't know on my JC character, but these are not listed at all in the Dalaran section, nor were they listed in areas such as Storm Peaks or Heroic dungeons where they are BOP drops off specific mobs/bosses.

**Comment by DFortun81** [comment]
This was fixed a bit ago. Please let me know if it's still missing a few.
