### ISSUE TITLE
Error Mousing Over an Object

### ISSUE THREAD

**Issue by Comicus** [DFortun81/ATT-WRATH-Classic#24]
Every time I mouse over Fjorn's Anvil in The Storm Peaks I get an error...

26x ATT-Classic\ATT-Classic-1.2.2.lua:3081: attempt to call global 'GetPlayerMapPosition' (a nil value)
[string "@ATT-Classic\ATT-Classic-1.2.2.lua"]:3081: in function `GetBestObjectIDForName'
[string "@ATT-Classic\ATT-Classic-1.2.2.lua"]:3528: in function <ATT-Classic\ATT-Classic.lua:3423>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Questie\Modules\Tooltips\MapIconTooltip.lua"]:406: in function <...eQuestie\Modules\Tooltips\MapIconTooltip.lua:39>

Locals:
name = "Fjorn's Anvil"
o = <table> {
 1 = 192071
 2 = 192060
}
mapID = 125
(*temporary) = nil
(*temporary) = "player"
(*temporary) = "attempt to call global 'GetPlayerMapPosition' (a nil value)"
objectNamesToIDs = <table> {
 Kaldorei Tome of Summoning = <table> {
 }
 Control Console = <table> {
 }
 Marvon's Chest = <table> {
 }
 Flame of Uzel = <table> {
 }
 Heart of the Ancients = <table> {
 }
 Ebenezer Rustlocke's Corpse = <table> {
 }
 Featherbeard's Remains = <table> {
 }
 Webwood Eggs = <table> {
 }
 Outhouse = <table> {
 }
 Cozzle's Footlocker = <table> {
 }
 Crystal Prison = <table> {
 }
 Sparktouched Crystal Defenses = <table> {
 }
 Egg of Onyxia = <table> {
 }
 Mound of Dirt = <table> {
 }
 Captain's Footlocker = <table> {
 }
 Tablet of Will = <table> {
 }
 Moontouched Feather = <table> {
 }
 Wanted! = <table> {
 }
 Large Jack-o'-Lantern = <table> {
 }
 Chest of Nesting = <table> {
 }
 Mrs. Dalson's Diary = <table> {
 }
 Relic Coffer = <table> {
 }
 Dusty Journal = <table> {
 }
 Velinde's Locker = <table> {
 }
 Hozen Totem = <table> {
 }
 Blackhoof Armaments = <table> {
 }
 Wooden Outhouse = <table> {
 }
 Dirt-stained Map = <table> {
 }
 Winter Veil Gift = <table> {
 }
 Wyrmtail = <table> {
 }
 Gently Shaken Gift = <table> {
 }
 Winterfall Cauldron = <table> {
 }
 Highperch Wyvern Egg = <table> {
 }
 Venom Bottle = <table> {
 }
 Remains of Lucien Sarkhoff = <table> {
 }
 Loose Dirt = <table> {
 }
 Saronite Bomb Stack = <table> {
 }
 Cache of the Legion = <table> {
 }
 Prototype Console = <table> {
 }
 Submerged Outhouse = <table> {
 }
 A Wrecked Raft = <table> {
 }
 A Small Pack = <table> {
 }
 Pillaclencher's Ornate Pillow = <table> {
 }
 Lillith's Dinner Table = <table> {
 }
 Matrix Punchograph 3005-C = <table> {
 }
 Scrying Bowl = <table> {
 }
 B'naar Control Console = <table> {
 }
 Wanted: Gath'Ilzogg = <table> {
 }
 Dart's Nest = <table> {
 }
 Plague Cauldron = <table> {
 }
 Ancient Chest = <table> {
 }
 Sealed Crate = <table> {
 }
 Bridenbrad's Possessions = <table> {
 }
 Polished Platter = <table> {
 }
 Lightforged Arch = <table> {
 }
 Flame of Imbel = <table> {
 }
 Necromantic Focus = <table> {
 }
 Brazier of the Dormant Flame = <table> {
 }
 Ruined Lifeboat = <table> {
 }
 Wrecked Row Boat = <table> {
 }
 Hodir's Horn = <table> {
 }
 Stone of West Binding = <table> {
 }
 Elder Mana'loa = <table> {
 }
 Seal of the Earth = <table> {
 }
 Hero's Call Board = <table> {
 }
 Stone of Shy-Rotam = <table> {
 }
 Rolf's corpse = <table> {
 }
 Scourge Meat Wagon = <table> {
 }
 A Soggy Scroll = <table> {
 }
 WANTED = <table> {
 }
 Tablet of Madness = <table> {
 }
 Wanted Poster: Deathclasp = <table> {
 }
 Old Jug = <table> {
 }
 The Scarab Gong = <table> {
 }
 Tallonkai's Dresser = <table> {
 }
 Glowing Gem = <table> {
 }
 Highborne Relic Fragment = <table> {
 }
 Adventure Board = <table> {
 }
 Carefully Wrapped Present = <table> {
 }
 Legion Communicator = <table> {
 }
 Steamy Romance Novel = <table> {
 }
 Dusty Reliquary = <table> {
 }
 Old Lion Statue = <table> {
 }
 Amberseed = <table> {
 }
 Telaar Bulletin Board = <table> {
 }
 Snow Mound = <table> {
 }
 Jordan's Hammer = <table> {
 }
 Wind Stone = <table> {
 }
 Marble Slab = <table> {
 }
 Shallow Grave = <table> {
 }
 Hodir's Spear = <table> {
 }
 Ravasaur Matriarch's Nest = <table> {
 }
 Ticking Present = <table> {
 }
 Brazier of Hatred = <table> {
 }
 Corrupted Windblossom = <table> {
 }
 Twilight Tome = <table> {
 }
 Wanted Poster = <table> {
 }
 Sprouted Frond = <table> {
 }
 Dark Iron Treasure Chest = <table> {
 }
 Chest of the Raven Claw = <table> {
 }
 Explosive Charge = <table> {
 }
 Document Chest = <table> {
 }
 Lightforged Crest = <table> {
 }
 Large Scarab Coffer = <table> {
 }
 Reinforced Fel Iron Chest = <table> {
 }
 Battered Tackle Box = <table> {
 }
 Alliance Bonfire = <table> {
 }
 Arngrim the Insatiable = <table> {
 }
 Crate of Ingots = <table> {
 }
 Assassination Notice = <table> {
 }
 Cache of Explosives = <table> {
 }
 Benedict's Chest = <table> {
 }
 Spire Spider Egg = <table> {
 }
 Massive Glowing Egg = <table> {
 }
 Stolen Explorers'

**Comment by DFortun81** [comment]
This has been fixed as of 1.2.4.
