### ISSUE TITLE
Lua Error caused by venomspite wanted poster

### ISSUE THREAD

**Issue by Draycos99** [DFortun81/ATT-WRATH-Classic#25]
Tooltip for wanted poster in Venomspite (Dragonblight, quest "Wanted: The Scarlet Onslaught") causes lua error:
"Message: bad argument DFortun81/AllTheThings#1 to '?' (outside of expected range -2147483648 to 2147483647 - Usage: local position = C_Map.GetPlayerMapPosition(uiMapID, unitToken))
Time: Sat Nov 19 20:07:13 2022
Count: 1
Stack: bad argument DFortun81/AllTheThings#1 to '?' (outside of expected range -2147483648 to 2147483647 - Usage: local position = C_Map.GetPlayerMapPosition(uiMapID, unitToken))
[string "=[C]"]: ?
[string "=[C]"]: in function `GetPlayerMapPosition'
[string "@Interface\AddOns\ATT-Classic\ATT-Classic.lua"]:3081: in function `GetBestObjectIDForName'
[string "@Interface\AddOns\ATT-Classic\ATT-Classic.lua"]:3528: in function <Interface\AddOns\ATT-Classic\ATT-Classic.lua:3423>
[string "=[C]"]: ?"

**Comment by DFortun81** [comment]
This has been fixed as of 1.2.4.
