### ISSUE TITLE
Profession Error

### ISSUE THREAD

**Issue by DiscipleDarkfriend** [DFortun81/ATT-WRATH-Classic#26]
Not sure what is causing this error but it happens each time I click on a profession icon. 

17x ATT-Classic\ATT-Classic-1.2.3.lua:9006: attempt to compare number with string
[string "@ATT-Classic\ATT-Classic-1.2.3.lua"]:9006: in function `GetSpellName'
[string "@ATT-Classic\ATT-Classic-1.2.3.lua"]:9075: in function <ATT-Classic\ATT-Classic.lua:9043>
[string "@ATT-Classic\ATT-Classic-1.2.3.lua"]:4001: in function <ATT-Classic\ATT-Classic.lua:3990>
[string "@ATT-Classic\ATT-Classic-1.2.3.lua"]:15740: in function <ATT-Classic\ATT-Classic.lua:15719>
[string "=[C]"]: ?
[string "=[C]"]: in function `CastSpellByID'
[string "@FrameXML\SecureTemplates.lua"]:377: in function `handler'
[string "@FrameXML\SecureTemplates.lua"]:625: in function <FrameXML\SecureTemplates.lua:569>

Locals:
spellID = 17
rank = "1"
spellName = "Power Word: Shield"
(*temporary) = 0
(*temporary) = <table> {
 Corruption = 7
 Holy Light = 9
 Healing Wave = 10
 Shadow Ward = 4
 Torment = 7
 Anguish = 3
 Devour Magic = 6
 Multi-Shot = 5
 Heroic Strike = 9
 Gift of the Wild = 3
 Starfire = 7
 Fishing = 6
 Frost Ward = 5
 Conjure Food = 8
 Revenge = 6
 Firebolt = 8
 Blessing of Might = 7
 Fireball = 12
 Backstab = 9
 Arcane Brilliance = 2
 Blessing of Wisdom = 6
 Dodge = 1
 Auto Attack = 1
 Suffering = 6
 Prayer of Fortitude = 3
 Prayer of Shadow Protection = 2
 Rejuvenation = 11
 Expert Riding = 3
 Cower = 4
 Blood Pact = 6
 Aspect of the Hawk = 7
 Lash of Pain = 7
 Greater Heal = 5
 Fire Shield = 6
 Arcane Torrent = 1
 Soothing Kiss = 5
 Basic Campfire = 1
 Healing Touch = 11
 Cleave = 3
 Ferocious Bite = 5
 Frostbolt = 11
 Cooking = 6
 Shoot = 1
 Battle Shout = 7
 Magic Resistance = 1
 Maul = 1
 Sacrifice = 7
 Journeyman Riding = 2
 Flame Shock = 6
 Shadow Bolt = 10
 Arcane Affinity = 1
 Prayer of Healing = 5
 Renew = 10
 Immolate = 8
 Arcane Missiles = 8
 Consume Shadows = 7
 Intercept = 3
 Conjure Water = 9
 Eviscerate = 9
 Serpent Sting = 9
 Artisan Riding = 4
 Feint = 5
 Strength of Earth Totem = 5
 Spell Lock = 2
 First Aid = 6
}
(*temporary) = nil
(*temporary) = "Power Word: Shield"
(*temporary) = nil
(*temporary) = 135940
(*temporary) = "attempt to compare number with string"
SpellIDToSpellName = <table> {
 66439 = "Lambent Eye of Zul"
 31076 = "Chain of the Twilight Owl"
 54213 = "Flask of Pure Mojo"
 31460 = "Netherweave Net"
 54981 = "Reinforced Cobalt Chestpiece"
 47046 = "Guardian's Alchemist Stone"
 23653 = "Nightfall"
 56005 = "Glacial Bag"
 24165 = "Hoodoo Hex"
 57029 = "Glyph of Holy Light"
 41415 = "The Black Pearl"
 16742 = "Enchanted Thorium Helm"
 33992 = "Enchant Chest - Major Resilience"
 25317 = "Ring of Silver Might"
 59589 = "Frostsavage Cowl"
 17638 = "Flask of Chromatic Resistance"
 35528 = "Flamescale Boots"
 60357 = "Elixir of Expertise"
 60613 = "Dark Iceborne Chestguard"
 18406 = "Runecloth Robe"
 66441 = "Radiant Eye of Zul"
 53958 = "Rigid Autumn's Glow"
 56006 = "Mysterious Bag"
 9972 = "Ornate Mithril Breastplate"
 57030 = "Glyph of Judgement"
 41160 = "Swiftstrike Shoulders"
 66442 = "Energized Eye of Zul"
 67466 = "Argent Warhorse"
 33993 = "Enchant Gloves - Blasting"
 69002 = "Onyxian Whelpling"
 29669 = "Black Felsteel Bracers"
 35529 = "Flamescale Leggings"
 30309 = "Felsteel Stabilizer"
 44488 = "Enchant Gloves - Precision"
 30565 = "Foreman's Enchanted Helmet"
 66443 = "Shattered Eye of Zul"
 31077 = "Coronet of Verdant Flame"
 47048 = "Sorcerer's Alchemist Stone"
 56007 = "Frostweave Bag"
 56519 = "Elixir of Mighty Mageblood"
 32485 = "Stylin' Purple Hat"
 57031 = "Glyph of Divinity"
 41161 = "Bindings of Lightning Reflexes"
 33738 = "Onslaught Elixir"
 33994 = "Enchant Gloves - Precise Strikes"
 25318 = "Ring of Twilight Shadows"
 35018 = "Purple Hawkstrider"
 17639 = "Wail of the Banshee"
 35530 = "Reinforced Mining Bag"
 26086 = "Felcloth Bag"
 44489 = "Enchant Shield - Defense"
 18407 = "Runecloth Tunic"
 66445 = "Turbid Eye of Zul"
 53960 = "Mystic Autumn's Glow"
 13620 = "Enchant Gloves - Fishing"
 47049 = "Redeemer's Alchemist Stone"
 56008 = "Shining Spellthread"
 57032 = "Glyph of Righteous Defense"
 41162 = "Shoulders of Lightning Reflexes"
 66446 = "Runed Cardinal Ruby"
 58312 = "Glyph of Blessing of Wisdom"
 33995 = "Enchant Gloves - Major Strength"
 35531 = "Flamescale Belt"
 60616 = "Enchant Bracers - Striking"
 30566 = "Foreman's Reinforced Helmet"
 22759 = "Flarecore Wraps"
 53961 = "Quick Autumn's Glow"
 54729 = "Winged Steed of the Ebon Blade"
 23399 = "Barbaric Bracers"
 47050 = "Assassin's Alchemist Stone"
 56009 = "Brilliant Spellthread"
 24167 = "Prophetic Aura"
 41163 = "Living Earth Bindings"
 66448 = "Delicate Cardinal Ruby"
 16744 = "Enchanted Thorium Leggings"
 33740 = "Adept's Elixir"
 33996 = "Enchant Gloves - Assault"
 35020 = "Blue Hawkstrider"
 35532 = "Enchanted Clefthoof Leggings"
 26087 = "Core Felcloth Bag"
 1127 = "Food"
 18408 = "Cindercloth Vest"

**Comment by DFortun81** [comment]
This build is very old. Please make sure you are on the latest (1.4.6) and let me know if you still experience this by opening a new ticket.
