### ISSUE TITLE
[Wrath Classic] Profession window claims there's no unlearned recipes

### ISSUE THREAD

**Issue by aSnejbjerg** [DFortun81/ATT-WRATH-Classic#3]
There's a bug when opening the profession window that shows me as complete with learning everything for my profession even though I'm clearly not done (Not even max level):
![image](https://user-images.githubusercontent.com/42168095/187765315-d8c253c2-f586-4c7e-993b-51d5e8a4d763.png)

**Comment by DFortun81** [comment]
This has been fixed. Tested with my Enchanter.
