### ISSUE TITLE
Got Lua Error on Load

### ISSUE THREAD

**Issue by Gogo1951** [DFortun81/ATT-WRATH-Classic#31]
Latest from CurseForge on Wrath.

10x ATT-Classic/ATT-Classic.lua:314: attempt to call method 'SetDepth' (a nil value)
[string "@ATT-Classic/ATT-Classic.lua"]:314: in main chunk

Locals:
app = <table> {
 GetDataSubMember = <function> defined @ATT-Classic/ATT-Classic.lua:215
 ExplorationAreaPositionDB = <table> {
 }
 SetScript = <function> defined @ATT-Classic/src/base.lua:29
 FlightPathDB = <table> {
 }
 ShowPopupDialogWithMultiLineEditBox = <function> defined @ATT-Classic/src/base.lua:131
 Race = "BloodElf"
 Settings = ATT-Classic-Settings {
 }
 refreshing = <table> {
 }
 ClassIndex = 4
 Presets = <table> {
 }
 ShowPopupDialog = <function> defined @ATT-Classic/src/base.lua:81
 FactionID = 1
 CategoryNames = <table> {
 }
 Faction = "Horde"
 GetTempDataSubMember = <function> defined @ATT-Classic/ATT-Classic.lua:242
 ObjectIcons = <table> {
 }
 Class = "ROGUE"
 CategoryIcons = <table> {
 }
 ShowPopupDialogWithEditBox = <function> defined @ATT-Classic/src/base.lua:101
 RaceDB = <table> {
 }
 L = <table> {
 }
 GetTempDataMember = <function> defined @ATT-Classic/ATT-Classic.lua:196
 SetDataSubMember = <function> defined @ATT-Classic/ATT-Classic.lua:205
 asset = <function> defined @ATT-Classic/src/base.lua:10
 RegisterEvent = <function> defined @ATT-Classic/src/base.lua:23
 SetDataMember = <function> defined @ATT-Classic/ATT-Classic.lua:181
 ObjectNames = <table> {
 }
 GetDataMember = <function> defined @ATT-Classic/ATT-Classic.lua:184
 ExplorationDB = <table> {
 }
 ObjectModels = <table> {
 }
 events = <table> {
 }
 PresetRWPs = <table> {
 }
 Level = 1
 GetName = <function> defined @ATT-Classic/src/base.lua:8
 _ = Frame {
 }
 UnregisterEvent = <function> defined @ATT-Classic/src/base.lua:26
}
L = <table> {
 TOGGLE_RANDOM = "Toggle ATT Random"
 I_ONLY_CARE_ABOUT_MY_MAIN = "|cff3399ffI only care about my main.|r"
 HEADER_NAMES = <table> {
 }
 TOGGLE_MINILIST = "Toggle ATT Mini List"
 TOGGLE_LOOTDROPS = "Toggle Loot/Drops/Items"
 OTHER_ROW_INSTRUCTIONS_AH = "|cff3399ffLeft Click to Expand/Collapse|r
|cff3399ffRight Click to Pop Out to Mini List|r
|cff3399ffShift + Click to Search the Auction House|r"
 FACTION_ID = "Faction ID"
 SAVED_TO_DJ_INSTANCES = <table> {
 }
 QUEST_ID = "Quest ID"
 HEADER_DESCRIPTIONS = <table> {
 }
 TOGGLE_BOEITEMS = "Toggle BoE/BoA Items"
 TOP_ROW_INSTRUCTIONS_AH = "|cff3399ffLeft Click and Drag to Move|r
|cff3399ffRight Click to Open the Settings Menu|r
|cff3399ffShift + Click to Search the Auction House|r"
 ABBREVIATIONS = <table> {
 }
 SPLIT = "Per Difficulty"
 DROP_RATE = "Drop Rate"
 LOGO_SMALL = "Interface\Addons\ATT-Classic\assets\logo_tiny"
 MOUNT_ID = "Mount ID"
 ITEM_ID_REMOVED_SHARED = "%s (%d) [+%d] were removed from your collection."
 INSTANCE_ACRONYM_TO_INSTANCE_ID = <table> {
 }
 TOGGLE_COLLECTEDTHINGS = "Toggle Collected Things"
 UNKNOWN_ON_CHARACTER = "|TInterface\Addons\ATT-Classic\assets\unknown:0|t |cffff9333Unknown on current character|r"
 ITEM_ID_REMOVED = "%s (%d) was removed from your collection."
 PREFERENCES = "Preferences"
 ARTIFACT_ID = "Artifact ID"
 CUSTOM_DIFFICULTIES = <table> {
 }
 REQUIRES_PVP = "|CFF00FFDEThis may require participation in PvP.|r"
 FACTION_MODE_TOOLTIP = "Turn this setting on if you want to see Account Mode data only for races and classes of your current faction."
 UNOBTAINABLE_ITEM_REASONS = <table> {
 }
 TITLE_ID = "Title ID"
 ITEM_ID_ADDED_RANK = "%s (%d) [Rank %d] was added to your collection."
 ALT_PROFESSION_TEXT_TO_ID = <table> {
 }
 RECENTLY_MADE_OBTAINABLE = "|CFFFF0000If this recently dropped for you (anywhere but Salvage
Crates), please post in Discord where you got it to drop!|r"
 TOGGLE_MAINLIST = "Toggle ATT Main List"
 COMPLETE_ICON = "|TInterface\Addons\ATT-Classic\assets\known_green:0|t"
 MUSIC_ROLL_ID = "Music Roll ID"
 TOGGLE_DEBUG_MODE = "Toggle Debug Mode"
 TITLE = "|cffb4b4ffATT-Classic|r"
 CURRENCY_ID = "Currency ID"
 ABBREVIATIONS_POST = <table> {
 }
 FILTER_ID_ICONS = <table> {
 }
 MINIMAP_MOUSEOVER_TEXT = "Right click to change settings.
Left click to open the Main List.
Ctrl +

**Comment by Gogo1951** [comment]
10x ATT-Classic/db/Wrath/Categories.lua:12: attempt to call local 'ach' (a nil value)
[string "@ATT-Classic/db/Wrath/Categories.lua"]:12: in main chunk

Locals:
_ = <table> {
 GetDataSubMember = <function> defined @ATT-Classic/ATT-Classic.lua:215
 ExplorationAreaPositionDB = <table> {
 }
 SetScript = <function> defined @ATT-Classic/src/base.lua:29
 FlightPathDB = <table> {
 }
 ShowPopupDialogWithMultiLineEditBox = <function> defined @ATT-Classic/src/base.lua:131
 Race = "BloodElf"
 Settings = ATT-Classic-Settings {
 }
 refreshing = <table> {
 }
 ClassIndex = 4
 Presets = <table> {
 }
 ShowPopupDialog = <function> defined @ATT-Classic/src/base.lua:81
 FactionID = 1
 CategoryNames = <table> {
 }
 Faction = "Horde"
 GetTempDataSubMember = <function> defined @ATT-Classic/ATT-Classic.lua:242
 ObjectIcons = <table> {
 }
 Class = "ROGUE"
 CategoryIcons = <table> {
 }
 ShowPopupDialogWithEditBox = <function> defined @ATT-Classic/src/base.lua:101
 RaceDB = <table> {
 }
 L = <table> {
 }
 Categories = <table> {
 }
 GetTempDataMember = <function> defined @ATT-Classic/ATT-Classic.lua:196
 SetDataSubMember = <function> defined @ATT-Classic/ATT-Classic.lua:205
 asset = <function> defined @ATT-Classic/src/base.lua:10
 RegisterEvent = <function> defined @ATT-Classic/src/base.lua:23
 SetDataMember = <function> defined @ATT-Classic/ATT-Classic.lua:181
 ObjectNames = <table> {
 }
 GetDataMember = <function> defined @ATT-Classic/ATT-Classic.lua:184
 ExplorationDB = <table> {
 }
 ObjectModels = <table> {
 }
 events = <table> {
 }
 PresetRWPs = <table> {
 }
 Level = 1
 GetName = <function> defined @ATT-Classic/src/base.lua:8
 _ = Frame {
 }
 UnregisterEvent = <function> defined @ATT-Classic/src/base.lua:26
}
rawset = <function> defined =[C]:-1
g = <function> defined @ATT-Classic/db/Wrath/Categories.lua:7
ach = nil
achcat = nil
aqd = nil
cat = nil
cl = nil
crit = nil
cu = nil
d = nil
e = nil
exp = nil
faction = nil
flt = nil
fp = nil
heir = nil
ho = nil
i = nil
inst = nil
m = nil
mnt = nil
mr = nil
n = nil
o = nil
p = nil
prof = nil
pt = nil
pvprank = nil
q = nil
qo = nil
r = nil
sp = nil
t = nil
title = nil
toy = nil
a = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
 41 = <table> {
 }
 42 = <table> {
 }
 43 = <table> {
 }
 44 = <table> {
 }
 45 = <table> {
 }
 46 = <table> {
 }
 47 = <table> {
 }
 48 = <table> {
 }
 49 = <table> {
 }
 50 = <table> {
 }
 51 = <table> {
 }
 52 = <table> {
 }
 53 = <table> {
 }
 54 = <table> {
 }
 55 = <table> {
 }
 56 = <table> {
 }
 57 = <table> {
 }
 58 = <table> {
 }
 59 = <table> {
 }
 60 = <table> {
 }
 61 = <table> {
 }
 62 = <table> {
 }
 63 = <table> {
 }
 64 = <table> {
 }
 65 = <table> {
 }
 66 = <table> {
 }
 67 = <table> {
 }
 68 = <table> {
 }
 69 = <table> {
 }
 70 = <table> {
 }
 71 = <table> {
 }
 72 = <table> {
 }
 73 = <table> {
 }
 74 = <table> {
 }
 75 = <table> {
 }
 76 = <table> {
 }
 77 = <table> {
 }
 78 = <table> {
 }
 79 = <table> {
 }
 80 = <table> {
 }
 81 = <table> {
 }
 82 = <table> {
 }
 83 = <table> {
 }
 84 = <table> {
 }
 85 = <table> {
 }
 86 = <table> {
 }
 87 = <table> {
 }
 88 = <table> {
 }
 89 = <table> {
 }
 90 = <table> {
 }
 91 = <table> {
 }
 92 = <table> {
 }
 93 = <table> {
 }
 94 = <table> {
 }
 95 = <table> {
 }
 96 = <table> {
 }
 97 = <table> {
 }
 98 = <table> {
 }

**Comment by Gogo1951** [comment]
Also got...

10x ATT-Classic/ATT-Classic.lua:1 (null)

**Comment by Gogo1951** [comment]
10x ATT-Classic/db/Wrath/Categories.lua:1 (null)

**Comment by Gogo1951** [comment]
9x Interface_Wrath\FrameXML\Bindings.xml:1 ATT-Classic/ATT-Classic.lua:1 (null)

**Comment by Gogo1951** [comment]
9x Interface_Wrath\FrameXML\Bindings.xml:1 ATT-Classic/db/Wrath/Categories.lua:1 (null)

**Comment by DFortun81** [comment]
This was fixed a couple versions back. Should have closed this ticket at that time.
