### ISSUE TITLE
"The Hammer May Fall" Not removed from List after completing followup Quest in Arathi

### ISSUE THREAD

**Issue by Haeldeus** [DFortun81/ATT-WRATH-Classic#34]
In WotLK Classic, The Quest ["The Hammer May Fall"](https://www.wowhead.com/wotlk/quest=676/) in Hillsbrad Foothills doesn't get removed from the List once you complete the followup Quest ["Call to Arms"](https://www.wowhead.com/wotlk/quest=677/) in Arathi Highlands. 
"Call to Arms" is obtainable without doing the Pre Quest and after completing it, you can neither accept nor complete "The Hammer May Fall" anymore, so it's kind of a breadcrumb Quest. 
But "The Hammer May Fall" doesn't get removed from the List for Hillsbrad Foothills and Arathi Highlands after completing "Call to Arms".

**Comment by DFortun81** [comment]
The Hammer May Fall now marks partial completion when you have completed Call to Arms (1/3).

Will be included with the next release.
