### ISSUE TITLE
Wrong quest listing Classic Era

### ISSUE THREAD

**Issue by Chaliff** [DFortun81/ATT-WRATH-Classic#35]
**_*SOLVED*_**

Hello guys, playing Classic Era and encountered a problem with Warlock quest in the Barrens - after completing the quest Fragments of the Orb of Orahil (https://www.wowhead.com/classic/quest=1799/fragments-of-the-orb-of-orahil) the game allows you to pick one of the two next quests - Shard of an Infernal (https://www.wowhead.com/classic/quest=4963/shard-of-an-infernal) OR Shard of a Felhound (https://www.wowhead.com/classic/quest=4962/shard-of-a-felhound). It is stated several times in the WowHead comments and validated by me in the game that you cannot take both quests, accepting one of them makes the other unavailable. So right now I cannot get 100% Quests section in Barrens because ATT states that I have not completed the quest Shard of an Infernal although I've chosen Shard of a Felhound to complete, which means that it's impossible to complete Shard of an Infernal for me. Attaching a screenshot, there is no possibility in game to complete both quests but Shard of an Infernal requires an item to get 2/2. hope you can solve it, have a nice week!
![Screenshot_3](https://user-images.githubusercontent.com/115579179/220398780-352acf94-c5e2-4ae7-817c-25064e15ec58.png)

**Comment by DFortun81** [comment]
This file is a work in progress still, I'll make sure to check this after the file is completed.

**Comment by Chaliff** [comment]
@DFortun81 can you pls also check these 3 things? Can you pls also reply something so I know that you are reading this :)


_**Classic Era**_


**1.** Uldaman requires you to complete Enchanting items even if you are not enchanter.

![Screenshot_2](https://user-images.githubusercontent.com/115579179/220711370-d4219d87-72ed-464a-8bd7-7443b2e9060a.png)

I looked it up on Discord and it seems like you fixed it for TBC, but not for Classic Era.

![Screenshot_6](https://user-images.githubusercontent.com/115579179/220711668-68f763c2-c4de-4baf-af18-ef398ff34208.png)


**2.** Hearts of the Lovers quest (Warlock Incubus quest) (https://www.wowhead.com/classic/quest=65593/hearts-of-the-lovers). So I completed the Orgrimmar quest for Incubus and right now Undercity quest is unavailable for me. I can't even take this quest, there is just no exclamation marks near Godrik Farsan or Carendin Haglar for me.

Here is what questie says - as you may see I completed Devourer of souls as stated:

![Screenshot_4](https://user-images.githubusercontent.com/115579179/220714157-1849126e-9fc3-4697-9e80-fc24757bc2ed.png)

But there is still nothing (both questgivers are above the river, but no available quests), I also checked the questgivers in person but have no screenshot, there are no quests at all:

![Screenshot_5](https://user-images.githubusercontent.com/115579179/220714434-7bf98248-6735-4035-a163-33f0ea64d635.png)

I also searched the discord server for this issue and found this, second message:

![image](https://user-images.githubusercontent.com/115579179/220714839-8f31d075-f2d9-40af-95d1-857917ed5337.png)

I also found several messages on Blizzard forums about this bug but no one replied. So can you please mark it as optional or either mark only one of the Incubus quests as obligatory (Only Undercity or Only Orgimmar) since there is no possible option to get 100% Undercity and Orgrimmar for now.

**3.** I have to collect items from the professions I don't have, so I have Tailoring and Mining, but in Crafted Items sections I need to collect items from other professions for some reason, is it ok? I can buy them on AH and complete these, but just don't see the point of this. I found a discussion on discord server that those items will be needed for crafting T0.5 Warlock set, so I see these items as uncompleted, is it true or is there a mistake?

![Screenshot_7](https://user-images.githubusercontent.com/115579179/220720168-55afdb44-9d84-40e9-8ead-67322e188408.png)

BTW: Curseforge states that the version for classic era is 1.3.0 although it states 1.2.7 (I have the latest version downloaded, seems like you forgot to update the number, hope it helps :)


_**Wrath Classic**_


P.S. I have already replied about the issue from the first message here. At Wrath Classic they have changed these two quests, so it's impossible to get 100% at Durotar atm: 

![image](https://user-images.githubusercontent.com/115579179/220715945-532fa60e-9ffb-4aa8-85a0-ebcfb9d929cc.png)

You can find explanation here - https://github.com/DFortun81/ATT-WRATH-Classic/issues/17

Hope it helps! Have a nice week! Let me know if I can help you fix it in any way, ready to assist.

**Comment by DFortun81** [comment]
I see your post, just really pretty busy most of the time. I'll see what I can do about it.

**Comment by DFortun81** [comment]
The Shard of the Infernal should be fixed now. The rest of them will need some additional investigation.

**Comment by Chaliff** [comment]
Hey @DFortun81! Can confirm that The Shard of the Infernal is fixed, now I have 100% in the Barrens, thanks a lot!! Would be so grateful if you can fix other things too, can assist in any way I can.

Several new things considering achievements in Classic Era:

1. The "Safe Deposit" achievement. It states "buy 7 additional bank slots", but in Classic Era there are only 6 so it is impossible to get this checked. See screenshot attached.

![Screenshot_5](https://user-images.githubusercontent.com/115579179/221426824-8d4eab51-2f23-4ec5-9188-020c1710cdaf.png)

2. The "Giddy Up!" achievement. As you may see on the screenshot, I have learned Undead Horsemanship, but achievement is still unchecked. But there is no Apprentice Riding skill in my Skill Menu, is Apprentice Riding skill even suitable for Classic Era? Or this may be connected with me being a warlock and getting a mount and a skill for free automatically. Can you pls check this up? I would suggest to change the condition to learning one of these skills: Kodo Riding, Raptor Riding, Undead Horsemanship or Wolf Riding and so on. Guess the same should be done with "Fast and Furious" achievement.

![Screenshot_4](https://user-images.githubusercontent.com/115579179/221426697-f0ad6284-42ca-471d-8a21-0d9afa7a8643.png)

3. After 1.3.9 (Classic) update, two new PVP achievements appeared, but both are saying Retrieving data. Are these leaders killing achievements are even suitable for Classic Era? Reloading doesn't help, they are not loading at all and It's not entirely clear what needs to be done there.

![Screenshot_3](https://user-images.githubusercontent.com/115579179/221426336-af42beb9-4723-4860-ac10-17c6cd67d20d.png)


Thanks for your work! Let me know if you need my help and have a nice week!

**Comment by DFortun81** [comment]
These are fixed on Git, sadly I didn't see this ticket before I released 1.4.8! It'll be included in 1.4.9 in a few weeks.
