### ISSUE TITLE
Data for Preist Quests is Off

### ISSUE THREAD

**Issue by Gogo1951** [DFortun81/ATT-WRATH-Classic#36]
The Tracker tells me I have yet to do the quest for Shadowguard, but... there's no quest available in TBC Classic.

![image](https://user-images.githubusercontent.com/55365231/182046731-3ea507bb-725b-4bd2-9373-d6cbbb6be003.png)

**Comment by DFortun81** [comment]
This is fixed in my latest commit. (not that it does any good for this situation since TBC Classic ain't a thing anymore, but I digress.)
