### ISSUE TITLE
Missing, Wrong Races, Wrong Classes by Nagi

### ISSUE THREAD

**Issue by Nagi-Warlock** [DFortun81/ATT-WRATH-Classic#52]
Hi, I gathered some more quests which are displayed as missing, of wrong race or class.

For reference I am a Horde Undead Female Warlock.
________________________________________________________________________________
- [x] 136 [WRONG RACES] - Captain Sander's Hidden Treasure - Can be done on Horde
- [x] 3741 [WRONG RACES] - Hilary's Necklace - Can be done on Horde
- [x] 4136 [WRONG RACES] - Ribbly Screwspigot - Can be done on Horde
________________________________________________________________________________
- [x] 4487 [WRONG RACES] - Summon Felsteed - Alliance Version but shows up for me as Horde? - Warlock
- [x] 4488 [WRONG RACES] - Summon Felsteed - Alliance Version but shows up for me as Horde? - Warlock
- [x] 4736 [WRONG RACES] - In Search of Menara Voidrender - Alliance Version but shows up for me as Horde? - Warlock
- [x] 4738 [WRONG RACES] - In Search of Menara Voidrender - Alliance Version but shows up for me as Horde? - Warlock
- [x] 4965 [WRONG RACES] - Knowledge of the Orb of Orahil - Alliance Version but shows up for me as Horde? - Warlock
- [x] 4968 [WRONG RACES] - Knowledge of the Orb of Orahil - Alliance Version but shows up for me as Horde? - Warlock
________________________________________________________________________________
- [x] 7168 [WRONG RACES] - Rise and Be Recognized - Alliance Version but shows up for me as Horde? - PvP Alterac
- [x] 7169 [WRONG RACES] - Honored Amongst the Guard - Alliance Version but shows up for me as Horde? - PvP Alterac
- [x] 7170 [WRONG RACES] - Earned Reverence - Alliance Version but shows up for me as Horde? - PvP Alterac
- [x] 7171 [WRONG RACES] - Legendary Heroes - Alliance Version but shows up for me as Horde? - PvP Alterac
- [x] 7172 [WRONG RACES] - The Eye of Command - Alliance Version but shows up for me as Horde? - PvP Alterac
________________________________________________________________________________
- [x] 8105 [MISSING] - The Battle for Arathi Basin! - Alliance Version but shows up for me as Horde? - PvP Arathi
- [x] 8114 [MISSING] - Control Four Bases - Alliance Version but shows up for me as Horde? - PvP Arathi
- [x] 8166 [MISSING] - The Battle for Arathi Basin! - Alliance Version but shows up for me as Horde? - PvP Arathi
- [x] 8167 [MISSING] - The Battle for Arathi Basin! - Alliance Version but shows up for me as Horde? - PvP Arathi
- [x] 8168 [MISSING] - The Battle for Arathi Basin! - Alliance Version but shows up for me as Horde? - PvP Arathi
- [x] 8120 [MISSING] - The Battle for Arathi Basin! - Horde Version - PvP Arathi
- [x] 8121 [MISSING] - Take Four Bases - Horde Version - PvP Arathi
- [x] 8169 [MISSING] - The Battle for Arathi Basin! - Horde Version - PvP Arathi
- [x] 8170 [MISSING] - The Battle for Arathi Basin! - Horde Version - PvP Arathi
- [x] 8171 [MISSING ]- The Battle for Arathi Basin! - Horde Version - PvP Arathi
________________________________________________________________________________
- [x] 8367 [MISSING] - For Great Honor - Horde Version - PvP
________________________________________________________________________________
- [x] 8883 [WRONG RACES] - Valadar Starsong - Both Factions - The Lunar Festival
________________________________________________________________________________
- [x] 9368 [MISSING] - The Festival of Fire - Horde Version - Midsummer Fire Festival
- [x] 9388 [WRONG RACES] - Flickering Flames in Kalimdor - Midsummer Fire Festival
- [x] 9389 [WRONG RACES] - Flickering Flames in the Eastern Kingdoms - Midsummer Fire Festival
________________________________________________________________________________
- [x] 172 [MISSING] - Children's Week - Horde Version - Children's Week
- [x] 910 [MISSING] - Down at the Docks - Horde Version - Children's Week
- [x] 911 [MISSING] - Gateway to the Frontier - Horde Version - Children's Week
- [x] 915 [MISSING] - You Scream, I Scream... - Horde Version - Children's Week
- [x] 925 [MISSING] - Cairne's Hoofprint - Horde Version - Children's Week
- [x] 1800 [MISSING] - Lordaeron Throne Room - Horde Version - Children's Week
- [x] 5502 [MISSING] - A Warden of the Horde - Horde Version - Children's Week
________________________________________________________________________________
- [x] 8900 [MISSING] - Dearest Elenia, - Horde Version - Love is in the Air
- [x] 8901 [MISSING] - Dearest Elenia, - Horde Version - Love is in the Air
- [x] 8902 [MISSING] - Dearest Elenia, - Horde Version - Love is in the Air
- [x] 8904 [MISSING] - Dangerous Love - Horde Version - Love is in the Air
- [x] 8979 [MISSING] - Fenstad's Hunch - Horde Version - Love is in the Air
- [x] 8980 [MISSING] - Zinge's Assessment - Horde Version - Love is in the Air
- [x] 8982 [MISSING] - Tracing the Source - Horde Version - Love is in the Air
- [x] 8983 [MISSING] - Tracing the Source - Horde Version - Love is in the Air
- [x] 8984 [MISSING] - The Source Revealed - Horde Version - Love is in the Air
- [x] 9029 [MISSING] - A Bubbling Cauldron - Both Factions - Love is in the Air
________________________________________________________________________________
- [x] 8913 [WRONG CLASSES] - An Earnest Proposition - Druid Version, but shows up for me as Warlock - T0.5
- [x] 8914 [WRONG CLASSES] - An Earnest Proposition - Hunter Version, but shows up for me as Warlock - T0.5
- [x] 8915 [WRONG CLASSES] - An Earnest Proposition - Mage Version, but shows up for me as Warlock - T0.5
- [x] 8916 [WRONG CLASSES] - An Earnest Proposition - Priest Version, but shows up for me as Warlock - T0.5
- [x] 8917 [WRONG CLASSES] - An Earnest Proposition - Rogue Version, but shows up for me as Warlock - T0.5
- [x] 8918 [WRONG CLASSES] - An Earnest Proposition - Shaman Version, but shows up for me as Warlock - T0.5
- [x] 8920 [WRONG CLASSES] - An Earnest Proposition - Warrior Version, but shows up for me as Warlock - T0.5
- [x] 8927 [WRONG CLASSES] - Just Compensation - Druid Version, but shows up for me as Warlock - T0.5
- [x] 8938 [WRONG CLASSES] - Just Compensation - Hunter Version, but shows up for me as Warlock - T0.5
- [x] 8939 [WRONG CLASSES] - Just Compensation - Mage Version, but shows up for me as Warlock - T0.5
- [x] 8940 [WRONG CLASSES] - Just Compensation - Priest Version, but shows up for me as Warlock - T0.5
- [x] 8941 [WRONG CLASSES] - Just Compensation - Rogue Version, but shows up for me as Warlock - T0.5
- [x] 8942 [WRONG CLASSES]  - Just Compensation - Shaman Version, but shows up for me as Warlock - T0.5
- [x] 8944 [WRONG CLASSES]  - Just Compensation - Warrior Version, but shows up for me as Warlock - T0.5

I imagine the other T0.5 quests behave similar, but I have not done them yet.
________________________________________________________________________________

I gathered some information from wowhead. I hope that this information is sufficient.

Thx,

Nagi Warlock - Lucifron DE

**Comment by DFortun81** [comment]
This appears to have been completed at some point since this ticket was created. If this is still an issue, please specify where you are seeing these quests in the addon and I'll investigate further.
