### ISSUE TITLE
Auction Frame conflict w/ Auctioneer

### ISSUE THREAD

**Issue by DanSheps** [DFortun81/ATT-WRATH-Classic#62]
I have ATT-Classic (0.7.4) installed, and Auctioneer 1.13.6727 (Previously 1.13.6718)

When I click the Auction House frame and drag, double click, etc, the frame itself bugs out.  If I disable window move in auctioneer, this problem goes away.

Willing to test to help debug.  Just let me know what you need me to do.

**Comment by DFortun81** [comment]
This fix has been applied. Sorry it took so long!
