### ISSUE TITLE
WotlK Classic: Paladin class quest 'Tome of Divinity' reappeared as incomplete

### ISSUE THREAD

**Issue by Pawgfarts** [DFortun81/ATT-WRATH-Classic#64]
As of the latest ATT update for Wotlk classic this class quest from Tiza Battleforge reappeared for me in my ATT log in ironforge. I have no way of accepting or completing it and I'm almost certain I already finished it years ago now. I'm unable to find the exact quest ID of the one displayed as available.

**Comment by Pawgfarts** [comment]
![WoWScrnShot_030523_050210](https://user-images.githubusercontent.com/66169124/222962031-cdc5c433-01c1-4bfc-8840-569ee17cf3e9.jpg)

Here's a screenshot with the ID showing. Apologies for not having that in the first post.

**Comment by DFortun81** [comment]
Fixed on latest git!
