### ISSUE TITLE
I see a bunch of "blank" Inscription Recipes

### ISSUE THREAD

**Issue by Gogo1951** [DFortun81/ATT-WRATH-Classic#65]
In Wrath.

I think I know all the minor, but there may be a few major recipes I have left to learn. I see a ton of blanks.

![image](https://user-images.githubusercontent.com/55365231/225060814-0459df44-0ce8-44c1-bd93-93b2d408edb8.png)

**Comment by DFortun81** [comment]
This should be fixed in the latest 1.4.6 release for ATT-Classic. (released today)
