### ISSUE TITLE
"Overachiever" Style Tooltips

### ISSUE THREAD

**Issue by Gogo1951** [DFortun81/ATT-WRATH-Classic#66]
It would be great to have AllTheThings show "Overachiever" style tooltips so players can better track the trivial stuff as they play.

Overachiever was an addon from when the game was real that showed if you needed to /love a critter, read a book, eat some food... a bunch of little quality of life things.

To my knowledge, nobody has brought back this sort of functionality in Classic.

![image](https://user-images.githubusercontent.com/55365231/226191060-972ca0fd-7dc4-4ade-82d1-abf8efe30569.png)

https://www.wowinterface.com/downloads/info11361-Overachiever.html

**Comment by DFortun81** [comment]
We already show tooltips on these sorts of things. Make sure you have Achievements turned on.
