### ISSUE TITLE
WOTLK LW missing Fur Lining - Arcane Resist

### ISSUE THREAD

**Issue by roeleert** [DFortun81/ATT-WRATH-Classic#68]
missing leatherworking recipe from the WOTLK database:

https://www.wowhead.com/wotlk/item=44563/pattern-fur-lining-arcane-resist

https://www.wowhead.com/wotlk/spell=57701/fur-lining-arcane-resist

**Comment by DFortun81** [comment]
This was fixed on Git already and can be found in the latest 1.4.6 release for ATT-Classic. (released today)
