### ISSUE TITLE
Cooking stuck at 429/430 ?

### ISSUE THREAD

**Issue by vgullotta8** [DFortun81/ATT-WRATH-Classic#69]
Am I doing something wrong? Is there a way to tell what quest or what I am doing wrong here? I have made the smoked desert dumplings a number of times, I had to make 10 of them for the quest in Silithus, I keep making them, but it doesn't complete this one last thing.

<img width="866" alt="image" src="https://user-images.githubusercontent.com/105075384/236595850-69f4bd22-7b1e-4824-b57f-c9be95b7a28c.png">

If you look at the tooltip, you'll see I have 2 currently in my bags. I have even eaten some to get the food buff, thinking maybe that was somehow related. 

Let me know if you can. Thanks.

**Comment by vgullotta8** [comment]
Also, just to add/clarify a few things (probably not necessary, but I had a few minutes and was thinking about this more):

I don't think there is a quest related to this. There was a quest to cook 10 of them in Silithus that I completed. This seems like it just wants me to craft the item, but I am new to ATT.

I am currently 450/450 cooking skill in-game, but there are exactly 430 quests and crafted items and other things that ATT lists to be completed to complete all the things. I have completed 429 out of 430 of them.

The item appears under Cooking > Crafted Item > Classic > Cooking > Everyday Cooking > [Smoked Desert Dumplings], which is why I think it is not a quest, but something else, and I am wondering if maybe I have to do it in a certain place or at a certain cooking fire or something along those lines? I am curious if there is anything in the code that might say that it is related to "questID=XXXX", or "locationID=Silithus" or maybe something that will tell me exactly what I need to do to get this to complete. 

I never did the quest to get the [Smoked Desert Dumplings] recipe where you have to kill Broodlord complete a huge long quest line after gaining a ton of rep I don't have, so I bought the recipe from someone that did do it. Perhaps it could be related to that quest line?

Maybe it was an old cooking daily and HAD to be done in Classic Vanilla and there is no way to complete this now? Maybe it is an old cooking daily that I am not aware of that is still completable?

I don't know, I am really just guessing here to see if maybe this jogs someone's memory or leads them in the right direction. Maybe it helps. If it's just a bug and you'll fix it in a future release, no big deal at all, I can wait if I know it's done, but I feel like I didn't do something. I may just go to Silithus and cook some there just to see If that does do it, I will update again with the solution, but I am not super hopeful lol

Thanks.

**Comment by DFortun81** [comment]
Open your Outdoor Zones and go to Kalimdor. If you are tracking Removed With Patch Loot or are not Exalted with Cenarion Circle, it's likely why you are seeing this as something to craft / keep as these are all materials of those associated quests.

**Comment by DFortun81** [comment]
Also for future reference, you can type /att <link the item> and it will popout a list of the things it wants you to do with a particular item if you are unsure.

**Comment by vgullotta8** [comment]
ahh interesting, so /att [smoked desert dumplings] tells me I have to turn in 4 of them for a quest in Silithus called Desert Survival Kits. I wonder if that is it. Ok I will check it out, I think there's a few quests I'll have to do to get to that point, but I'll check it out. Thanks for the help.

**Comment by DFortun81** [comment]
Glad we could help!
