### ISSUE TITLE
ATT doesn't register heroic keys as completed when bought

### ISSUE THREAD

**Issue by aSnejbjerg** [DFortun81/ATT-WRATH-Classic#7]
It seems ATT can't see items in my keyring. Maybe because something changed about the keyring?
Example:
![image](https://user-images.githubusercontent.com/42168095/189521118-d4a141ed-84e9-4cb1-9aee-81fc48c98dd4.png)

![image](https://user-images.githubusercontent.com/42168095/189521124-61546b6e-7eec-4b12-be74-942d2e8ad499.png)

**Comment by DFortun81** [comment]
This has been fixed.
