### ISSUE TITLE
Achievement not showing in HoS when completed on another character

### ISSUE THREAD

**Issue by aSnejbjerg** [DFortun81/ATT-WRATH-Classic#71]
The image below shows I haven't completed it on my character and it's not showing: 
![image](https://github.com/DFortun81/ATT-WRATH-Classic/assets/42168095/aeccbb30-fc85-4dc7-adcb-e6e8e2bcf483)

These are my settings: 
![image](https://github.com/DFortun81/ATT-WRATH-Classic/assets/42168095/38101f65-fb1f-47f3-a700-988f33ab951e)

**Comment by DFortun81** [comment]
This should have been fixed already. It was an issue with a holiday filter. Please reopen this ticket if it's a problem.
