### ISSUE TITLE
Wrath Phase 3 data

### ISSUE THREAD

**Issue by aSnejbjerg** [DFortun81/ATT-WRATH-Classic#78]
Is it being worked on?

Do you guys need help with it, because I'd gladly help out :)

**Comment by DFortun81** [comment]
What data is missing? Make sure Phase 3 is checked in the phases section

**Comment by aSnejbjerg** [comment]
It was activated, yes.
However I decided to reinstall the addon because of your answer, it's all there now!

Thank you very much for the awesome work you do here!
