### ISSUE TITLE
WOTLK Inscription Spell ID's Missing from Database

### ISSUE THREAD

**Issue by vae-32** [DFortun81/ATT-WRATH-Classic#8]
This is not a complete list - I am sure more of the Wrath glyphs are missing, but this is what I have encountered so far through leveling up my inscription to 330. They are all giving the below error in chat that they are missing their spell ID's in the ATT database.

![Capture](https://user-images.githubusercontent.com/113408023/189803571-592d7c0e-11bf-47de-959c-5257ca6b947c.PNG)

Glyph of Blood Strike
Glyph of Rune Tap
Glyph of Unbreakable Armor
Glyph of Plague Strike
Glyph of Rake
Glyph of Shred
Glyph of Starfire
Glyph of Rapid Fire
Glyph of Mage Armor
Glyph of Arcane Blast
Glyph of Ice Block
Glyph of Flash of Light
Glyph of Holy Nova
Glyph of Feint
Glyph of Garrote
Glyph of Windfury Weapon
Glyph of Earthliving Weapon
Glyph of Lava Lash
Glyph of Succubus
Glyph of Sweeping Strikes

**Comment by DFortun81** [comment]
All of these issues should be fixed in the latest 1.4.6 release for ATT-Classic. (released today)

Please let me know otherwise. (open a new ticket!)
